
INSERT INTO `classe` VALUES 
(31, 'Anti-inflamatórios não esteroides (AINEs)','Etoricoxibe', 'Varfarina', '13% de aumento no tempo de protrombina.'), 
(32, 'Anti-inflamatórios não esteroides (AINEs)','Etoricoxibe', 'Metotrexato', 'Etoricoxibe na dose de 120 mg aumentou a concentração plasmática do metotrexato em 28% (conforme avaliado pela AUC) e reduziu a depuração renal do metotrexato em 13%.'),
(33, 'Anti-inflamatórios não esteroides (AINEs)','Etoricoxibe', 'Rifampicina', 'Reduz em 65% a área sob a curva (AUC) da concentração plasmática do etoricoxibe.'),
(34, 'Anti-inflamatórios não esteroides (AINEs)','Atroveran DIP', 'Ciclosporinas','Redução dos níveis de ciclosporina no sangue.'),
(35, 'Anti-inflamatórios não esteroides (AINEs)','Atroveran DIP', 'Metotrexato','Aumento da toxicidade sanguínea do metotrexato particularmente em pacientes idosos. (colocar)'),
(36, 'Anti-inflamatórios não esteroides (AINEs)','Atroveran DIP', 'Ácido acetilsalicílico','edução do efeito do ácido acetilsalicílico na agregação plaquetária'),
(37, 'Anti-inflamatórios não esteroides (AINEs)','Ácido Mefenâmico', 'Anticoagulantes','O Ácido Mefenâmico desloca a varfarina dos sítios de ligação à proteína e pode aumentar a resposta aos anticoagulantes orais. '),
(38, 'Anti-inflamatórios não esteroides (AINEs)','Ácido Mefenâmico','Anti-hipertensivos','O ácido mefenâmico diminui a eficácia desses medicamentos.'),
(39, 'Anti-inflamatórios não esteroides (AINEs)','Ácido Mefenâmico', 'Corticosteroides','Aumento do risco de ulceração gastrintestinal ou sangramento'),
(40, 'Anti-inflamatórios não esteroides (AINEs)','Ácido Mefenâmico', 'Ciclosporina','Devido aos efeitos nas prostaglandinas renais, os AINEs como o ácidomefenâmico, podem aumentar o risco de nefrotoxicidade com a ciclosporina'),
(41, 'Anti-inflamatórios não esteroides (AINEs)','Ácido Mefenâmico', 'Agentes hipoglicemiantes','Alterações no efeito dos agentes hipoglicemiantes orais na presença de AINEs. '),
(42, 'Anti-inflamatórios não esteroides (AINEs)','Ácido Mefenâmico', 'Lítio','A interação ocorrida com os AINEs com este fármaco é por eles inibirem a síntese de prostaglandinas renais. Pode verificar-se uma maior reabsorção tubular do lítio, e ocorrência de níveis sanguíneos tóxicos. '),
(43, 'Anti-inflamatórios não esteroides (AINEs)','Ácido Mefenâmico', 'Metotrexato','Aumento dos níveis plasmáticos de metotrexato'),
(44, 'Anti-inflamatórios não esteroides (AINEs)','Ácido Mefenâmico', 'Cetorolaco','Aumento do risco de sangramento gastrointestinal'),
(45, 'Anti-inflamatórios não esteroides (AINEs)','Ácido Mefenâmico', 'Ginkgo biloba','Aumento do risco de sangramento'),
(46, 'Anti-inflamatórios não esteroides (AINEs)','Ácido Mefenâmico', 'Inibidores seletivos da recaptação de serotonina ','Aumentam o risco de sangramento gastrointestinal'), 
(47, 'Anti-inflamatórios não esteroides (AINEs)','Diclofenaco Sódico', 'Lítio','A interação ocorrida com os AINEs com este fármaco é por eles inibirem a síntese de prostaglandinas renais. Pode verificar-se uma maior reabsorção tubular do lítio, e ocorrência de níveis sanguíneos tóxicos.'),
(48, 'Anti-inflamatórios não esteroides (AINEs)','Diclofenaco Sódico', 'Digoxina', 'elevação das concentrações plasmáticas de digoxina.'),
(49, 'Anti-inflamatórios não esteroides (AINEs)','Diclofenaco Sódico', 'Diuréticos ou anti-hipertensivos','O uso concomitante de diclofenaco com diuréticos ou anti-hipertensivos  pode diminuir o efeito anti-hipertensivo.'),
(50, 'Anti-inflamatórios não esteroides (AINEs)','Diclofenaco Sódico','Medicamentos conhecidos por causar hipercalemia','O tratamento concomitante com diuréticos poupadores de potássio, ciclosporina, tacrolimo ou trimetoprima podem ser associados com o aumento dos níveis séricos de potássio'),
(51, 'Anti-inflamatórios não esteroides (AINEs)','Diclofenaco Potássico','Lítio','A interação ocorrida com os AINEs com este fármaco é por eles inibirem a síntese de prostaglandinas renais. Pode verificar-se uma maior reabsorção tubular do lítio, e ocorrência de níveis sanguíneos tóxicos.'),
(52, 'Anti-inflamatórios não esteroides (AINEs)','Diclofenaco Potássico','Digoxina','  elevação das concentrações plasmáticas de digoxina.'),
(53, 'Anti-inflamatórios não esteroides (AINEs)','Diclofenaco Potássico','Diuréticos ou anti-hipertensivos','O uso concomitante de diclofenaco com diuréticos ou anti-hipertensivos  pode diminuir o efeito anti-hipertensivo.'),                                                                                                                           
(54, 'Anti-inflamatórios não esteroides (AINEs)','Diclofenaco Potássico','Medicamentos conhecidos por causar hipercalemia','O tratamento concomitante com diuréticos poupadores de potássio, ciclosporina, tacrolimo ou trimetoprima podem ser associados com o aumento dos níveis séricos de potássio.'),
(55, 'Anti-inflamatórios não esteroides (AINEs)','Etoricoxibe Diuréticos', 'Inibidores da enzima conversora de angiotensina (ECA) e bloqueadores do receptor de angiotensina II (BRAs): AINEs, incluindo os inibidores seletivos da COX-2','Podem diminuir o efeito anti-hipertensivo dos diuréticos, dos inibidores da ECA e dos BRAs.'),
(56, 'Anti-inflamatórios não esteroides (AINEs)','Etoricoxibe','Lítio','A interação ocorrida com os AINEs com este fármaco é por eles inibirem a síntese de prostaglandinas renais. Pode verificar-se uma maior reabsorção tubular do lítio, e ocorrência de níveis sanguíneos tóxicos.'),
(57, 'Anti-inflamatórios não esteroides (AINEs)','Etoricoxibe','Ácido acetilsalicílico','Aumento da incidência de úlceras ou de outras complicações do trato gastrintestinal em comparação com o uso de Etoricoxibe isoladamente'),
(58, 'Anti-inflamatórios não esteroides (AINEs)','Etoricoxibe','anticoncepcionais orais','Ocorre um aumento na concentração do etinilestradiol que possui em anticoncepcionais orais. ');
